### ISSUE TITLE
Bunsen tint2 session not working when multi tint2rc file

### ISSUE THREAD

**Issue by samwhelp** [BunsenLabs/bunsen-blob#2]
# Bunsen tint2 session not working when multi tint2rc file

## Demo Blob

* [Two-Dark-Main-Bottom-Sub-Top](https://github.com/samwhelp/bunsenlabs-adjustment/tree/main/prototype/main/bunsen-config/Main/asset/overlay/etc/skel/.config/blob/Two-Dark-Main-Bottom-Sub-Top) / [tint2](https://github.com/samwhelp/bunsenlabs-adjustment/tree/main/prototype/main/bunsen-config/Main/asset/overlay/etc/skel/.config/blob/Two-Dark-Main-Bottom-Sub-Top/user/.config/tint2)

## Description

* Two-Dark-Main-Bottom-Sub-Top / tint2 / [tint2-sessionfile](https://github.com/samwhelp/bunsenlabs-adjustment/blob/main/prototype/main/bunsen-config/Main/asset/overlay/etc/skel/.config/blob/Two-Dark-Main-Bottom-Sub-Top/user/.config/tint2/tint2-sessionfile)

```
.config/tint2/two-dark-main-bottom.tint2rc
.config/tint2/two-dark-sub-top.tint2rc
```

after executing [bl-obthemes](https://github.com/BunsenLabs/bunsen-blob/blob/boron/bin/bl-obthemes#L479-L538),

it will rewrite `Two-Dark-Main-Bottom-Sub-Top / tint2 / tint2-sessionfile`

```
.config/tint2/two-dark-main-bottom.tint2rc.config/tint2/two-dark-sub-top.tint2rc
```

so apply blob `Two-Dark-Main-Bottom-Sub-Top` whould not working.

~~I created a [pull request #1](https://github.com/BunsenLabs/bunsen-blob/pull/1) to fix this situation.~~

Please merge [pull request #3](https://github.com/BunsenLabs/bunsen-blob/pull/3).

**Comment by samwhelp** [comment]
I'm sorry.
I review the code.
I close [pull request #1 ](https://github.com/BunsenLabs/bunsen-blob/pull/1),
The [pull request #1 ](https://github.com/BunsenLabs/bunsen-blob/pull/1)  is also working,
But the [pull request #3](https://github.com/BunsenLabs/bunsen-blob/pull/3) much better.
So please merge the [pull request #3](https://github.com/BunsenLabs/bunsen-blob/pull/3).

**Comment by johnraff** [comment]
Thank you for this improvement @samwhelp 

If I were rewriting this code now, I would store the tint2 file paths in an array instead of separating them with a semicolon.
In fact, the function upgradeBlobs() should no longer be necessary, and we will probably stop using it in BunsenLabs Carbon, but anyway, whether it is used or not, it should be correct!

I will merge your PR #3  which fixes the issue by quoting the semicolon.
Thanks again!

**Comment by johnraff** [comment]
Done.
